# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: github-runner
    

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Start API in background
      run: |
        nohup dotnet run --project Api &
    - name: Install curl for debugging
      run: sudo apt-get install -y curl
    - name: Add certificate
      run: |
        sudo apt-get install ca-certificates
        echo "${{ secrets.SELF_SIGNED_CERT }}" | base64 --decode > mycert.pem
        sudo cp mycert.pem /usr/local/share/ca-certificates/
        sudo update-ca-certificates
        sudo cp cert.pem /etc/ssl/certs/
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
      
    - name: Kill API process
      if: always()
      run: |
        pkill dotnet
