# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Start API in background
      run: |
        nohup dotnet run --project Api &
    - name: Wait for API to start
      run: |
        sleep 3
    - name: Add Dev Https Certs
      run: sudo dotnet dev-certs --trust
        
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
      
    - name: Kill API process
      if: always()
      run: |
        pkill dotnet
